web:
  restart: always
  image: containers.cisco.com/rafacarv/cmx-finder:latest
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  #env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  #image: tutum/nginx:latest
  image: containers.cisco.com/rafacarv/nginx:latest
  #build: ./nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  labels:
    io.rancher.sidekicks: web  
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  labels:
    io.rancher.sidekicks: data
  ports:
    - "5432:5432"